### ISSUE TITLE
Requirements conflict: torchvision requires torch==1.5.1

### ISSUE THREAD

**Issue by krisgesling** [castorini/howl#34]
Just doing a fresh setup and saw this mismatch when pip installing the requirements:
```
ERROR: torchvision 0.6.1 has requirement torch==1.5.1, but you'll have torch 1.5.0 which is incompatible.
```
https://github.com/pytorch/vision/releases/tag/v0.6.1

**Comment by ljj7975** [comment]
when you follow the instruction on https://pytorch.org/get-started/previous-versions/
you should be running 
`conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=xxx -c pytorch`.

otherwise
`conda install pytorch==1.5.0 torchvision==0.6.0 -c pytorch`

So you shouldn't be seeing the issue unless installing them one by one

Please re-open the issue if this does not solve the issue
