### ISSUE TITLE
Example of the CTC loss usage

### ISSUE THREAD

**Issue by joemayer1** [castorini/howl#42]
Great project.

I've noticed that the CTC loss is implemented in the code but no usage example is provided in the README.
Tried it myself but got some errors, also it seems that the labels are still binary.

Would be great to get an example of how to use this setup.

**Comment by ljj7975** [comment]
`OBJECTIVE='ctc'` does the job
if you look at https://github.com/castorini/howl/blob/master/howl/run/train.py#L97, it is designed to use ctc when objective is not `frame`

However, only `seq-lstm` is implemented to support 'ctc' loss due to the different output shape the loss function expects (as you have already noticed)
If you wish to use ctc with the other models, you can try to reshape the output for those models.
If my understanding is correct, you can try generating seq-gru and seq-las models

here is sample command (note the objective and model settings)
```
 VOCAB='[" hey","fire","fox"]' BATCH_SIZE=16 INFERENCE_THRESHOLD=0 NUM_EPOCHS=5 NUM_MELS=40 INFERENCE_SEQUENCE=[0,1,2] MAX_WINDOW_SIZE_SECONDS=0.5 OBJECTIVE='ctc' python -m howl.run.train --model seq-lstm --workspace workspaces/ctc -i /data/speaker-id-split-medium
```
it's been awhile since I have trained this model so not sure if it will work 100% but the training will perform fine.
it would be great if you can let me know how the training / detection works with it :)

**Comment by ljj7975** [comment]
also you might want to start from the setting here
https://github.com/castorini/howl/blob/master/envs/rnn.env

**Comment by ljj7975** [comment]
CTC loss added!
