### ISSUE TITLE
printing out how many instances of vocab is captured from dataset generation

### ISSUE THREAD

**Issue by ljj7975** [castorini/howl#57]
I have tried to generate datasets for `love you`

However most of the samples are captured for `you` and samples for `love` was only a handful.

It would be beneficial to see how many instances are captured for each vocab and keep the amount simliar

**Comment by Alex-Beh** [comment]
Yes it might be useful. I try to generate custom dataset and do the training. But the performance is not good because there is some bias in the generated dataset.

**Comment by ljj7975** [comment]
@Alex-Beh it seems like you have been trying to a datasets for custom wakeword. you might find scripts in #55 useful.
I still need to test and fix a couple thing but it should be a good reference.

**Comment by Alex-Beh** [comment]
I try to run the generate_dataset.sh and the train_model.sh . Do we need to set the [VOCAB ](echo ">>> training a model for ${VOCAB}; model will be stored at ${WORKSPACE_PATH}")variable before we start training? Because it still show  `labeler vocab:  [' hey', 'fire', 'fox']` ....

As I described in [this issue](https://github.com/castorini/howl/issues/37#issuecomment-758475061), the confusion matrix is `ConfusionMatrix(tp=0, fp=0, tn=0, fn=0)` most of the time and and only the few episode is `ConfusionMatrix(tp=0, fp=0, tn=806, fn=0)`. Is that something wrong with the training process?

**Comment by ljj7975** [comment]
let me try it myself and get you working version
